### PR TITLE
fix: release streams resource while loading config

### LINKED ISSUE #112: Unreleased Resource: Streams
https://github.com/XiaoMi/pegasus-java-client/blob/33a9a05f1929293275a1952dbd4457923f83e1f9/src/main/java/com/xiaomi/infra/pegasus/client/PConfigUtil.java#L64

The program can potentially fail to release a system resource.

### PR DESCRIPTION
**Pull request by totalo**
fixed #112

### CODE REVIEW

File: src/main/java/com/xiaomi/infra/pegasus/client/PConfigUtil.java [hunk 1]
```diff
@@ -61,13 +61,13 @@ public static Properties loadConfiguration(String configPath) throws PException
...
                 new FileInputStream(configPath.substring(PConfigUtil.LOCAL_FILE_PREFIX.length()))));
       } else if (PConfigUtil.isResource(configPath)) {
-        InputStream stream =
+        try (InputStream stream =
             PegasusClient.class.getResourceAsStream(
-                configPath.substring(PConfigUtil.RESOURCE_PREFIX.length()));
-        if (stream == null) {
+                configPath.substring(PConfigUtil.RESOURCE_PREFIX.length()))) {
+          config.load(stream);
+        } catch (NullPointerException e) {
```
Comment (neverchanje) [inline src/main/java/com/xiaomi/infra/pegasus/client/PConfigUtil.java:68]: Thank you for your contribution, but I'm afraid this is not a cool way to fix the issue.
Issue #112  indicates that the stream was not closed after usage. I don't see wrapping around with a try-catch can fix this.

The following solution may be better:

```diff
        InputStream stream =
            PegasusClient.class.getResourceAsStream(
                configPath.substring(PConfigUtil.RESOURCE_PREFIX.length()));
        if (stream == null) {
          throw new PException("config resource not found: " + configPath);
        }
        config.load(stream);
+       stream.close();
```

Comment (totalo) [reply src/main/java/com/xiaomi/infra/pegasus/client/PConfigUtil.java:68]: Ok, Fine, But I want to know why can't we use try-with-resource?

Comment (neverchanje) [reply src/main/java/com/xiaomi/infra/pegasus/client/PConfigUtil.java:68]: You don't fix anything using try-with-resource AFAIS. There's no reason to change the code if nothing fixed.
What do you think of the benefit that adding try-catch here can bring?

Comment (totalo) [reply src/main/java/com/xiaomi/infra/pegasus/client/PConfigUtil.java]: Thank you,😁 I understand that using it there is not a good way.

File: src/main/java/com/xiaomi/infra/pegasus/client/PConfigUtil.java [hunk 2]
```diff
@@ -68,6 +68,7 @@ public static Properties loadConfiguration(String configPath) throws PException
           throw new PException("config resource not found: " + configPath);
         }
         config.load(stream);
+        stream.close();
```
Comment (Shuo-Jia) [inline src/main/java/com/xiaomi/infra/pegasus/client/PConfigUtil.java:71]: if here need manual-close, the above `stream` also need close, maybe you can modify:
```java
      InputStream stream = null;
      if (PConfigUtil.isZkPath(configPath)) {
        stream = new ByteArrayInputStream(PConfigUtil.loadConfigFromZK(configPath));
      } else if (PConfigUtil.isLocalFile(configPath)) {
        stream = new BufferedInputStream(
            new FileInputStream(configPath.substring(PConfigUtil.LOCAL_FILE_PREFIX.length())));
      } else if (PConfigUtil.isResource(configPath)) {
        stream =
            PegasusClient.class.getResourceAsStream(
                configPath.substring(PConfigUtil.RESOURCE_PREFIX.length()));
      } else {
        throw new PException(
            "configPath format error, "
                + "should be local file format as 'file:///path/to/config', "
                + "or zookeeper path format as 'zk://host1:port1,host2:port2,host3:port3/path/to/config', "
                + "or java resource format as 'resource:///path/to/config', "
                + "but actual configPath is "
                + configPath);
      }
      if (stream == null) {
        throw new PException("config resource not found: " + configPath);
      }
      config.load(stream);
      return config;
```

Comment (totalo) [reply src/main/java/com/xiaomi/infra/pegasus/client/PConfigUtil.java]: Yeh, Got its!

File: src/main/java/com/xiaomi/infra/pegasus/client/PConfigUtil.java [hunk 3]
```diff
@@ -77,13 +74,25 @@ public static Properties loadConfiguration(String configPath) throws PException
...
       if (e instanceof PException) {
         throw (PException) e;
       } else {
         throw new PException(e);
       }
+    } finally {
+      if (stream != null) {
+        try {
+          stream.close();
+        } catch (Exception ignore) {
```
Comment (Shuo-Jia) [inline src/main/java/com/xiaomi/infra/pegasus/client/PConfigUtil.java:92]: Better output `debug` info？

File: src/main/java/com/xiaomi/infra/pegasus/client/PConfigUtil.java [hunk 4]
```diff
@@ -77,13 +74,25 @@ public static Properties loadConfiguration(String configPath) throws PException
                 + "but actual configPath is "
                 + configPath);
       }
+      if (stream == null) {
+        throw new PException("config resource not found: " + configPath);
+      }
+      config.load(stream);
```
Comment (neverchanje) [inline src/main/java/com/xiaomi/infra/pegasus/client/PConfigUtil.java:80]:
```suggestion
      config.load(stream);
      stream.close();
```

Close here. So you don't have to add another try-catch after `finally`.

File: src/main/java/com/xiaomi/infra/pegasus/client/PConfigUtil.java [hunk 5]
```diff
@@ -77,13 +74,25 @@ public static Properties loadConfiguration(String configPath) throws PException
...
         throw new PException(e);
       }
+    } finally {
+      if (stream != null) {
+        try {
+          stream.close();
+        } catch (Exception ignore) {
+          // ignore
+        }
+      }
```
Comment (neverchanje) [inline src/main/java/com/xiaomi/infra/pegasus/client/PConfigUtil.java:95]:
```suggestion
```

See my comment above

File: src/main/java/com/xiaomi/infra/pegasus/client/PConfigUtil.java (hunk 4 above)
Comment (totalo) [reply src/main/java/com/xiaomi/infra/pegasus/client/PConfigUtil.java:80]: If `config.load` throws an exception, resources cannot be released normally.😂

File: src/main/java/com/xiaomi/infra/pegasus/client/PConfigUtil.java (hunk 3 above)
Comment (totalo) [reply src/main/java/com/xiaomi/infra/pegasus/client/PConfigUtil.java:92]: Abnormal shutdown of resources is not the business logic of the system, I think it can be ignored, what do you think?

File: src/main/java/com/xiaomi/infra/pegasus/client/PConfigUtil.java (hunk 4 above)
Comment (neverchanje) [reply src/main/java/com/xiaomi/infra/pegasus/client/PConfigUtil.java:80]: Sure. But the stream will not be closed before `config.load` works are done.

```suggestion
      config.load(stream); // if any exception, it will be thrown out, won't steps down to `stream.close()`
      stream.close();
```

Comment (totalo) [reply src/main/java/com/xiaomi/infra/pegasus/client/PConfigUtil.java:80]: Although the `config.load` works is not completed, I think the resource also  needs to be released.

File: src/main/java/com/xiaomi/infra/pegasus/client/PConfigUtil.java (hunk 3 above)
Comment (neverchanje) [reply src/main/java/com/xiaomi/infra/pegasus/client/PConfigUtil.java:92]: @totalo  You can throw it as a `PException`. Don't ignore any exception if we can do better.

```diff
-  // ignore
+  throw new PException(e);
```

Comment (totalo) [reply src/main/java/com/xiaomi/infra/pegasus/client/PConfigUtil.java:92]: Yeh，Got it! Thank you~
